<?php
/**
 * @file
 * Functions for the doubleclick_floodlight tag module.
 */

/**
 * Implements hook_help().
 */
function doubleclick_floodlight_help($path) {
  switch ($path) {
    case 'admin/help#doubleclick_floodlight':
      $output = '<p>' . t('The Doubleclick Floodlight module allows you to integrate Floodlight Tags onto your site.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function doubleclick_floodlight_permission() {
  return array(
    'administer doubleclick_floodlight' => array(
      'title' => t('Administer Doubleclick Floodlight'),
      'description' => t('Users can enable, edit, and disable Doubleclick Floodlight tag.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function doubleclick_floodlight_menu() {
  $items = array();

  $items['admin/config/services/floodlight'] = array(
    'title' => 'Doubleclick Floodlight Settings',
    'type' => MENU_LOCAL_TASK,
    'description' => "Configure tag parameters.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('doubleclick_floodlight_admin_settings'),
    'access arguments' => array('administer doubleclick_floodlight'),
    'file' => 'doubleclick_floodlight.admin.inc',
    'weight' => 5,
  );

  return $items;
}

/**
 * Implements hook_page_build().
 */
function doubleclick_floodlight_page_build(&$page) {
  $enabled = variable_get('doubleclick_floodlight_enabled', 0);
  // If doubleclick_floodlight is enabled and configured we want to display it on all pages except admin pages.
  if ($enabled && !path_is_admin(current_path())) {
    $region = variable_get('doubleclick_floodlight_region', 'page_top');
    $account_id = variable_get('doubleclick_floodlight_account_id', '');
    $type = variable_get('doubleclick_floodlight_type', '');
    $cat = variable_get('doubleclick_floodlight_cat', '');
    $show_standard = variable_get('doubleclick_floodlight_show_standard', 0);
    $show_unique = variable_get('doubleclick_floodlight_show_unique', 0);

    if (!empty($account_id)) {
      if ($show_standard) {
        $std_pix = doubleclick_floodlight_standard_pixel($account_id, $type, $cat);
        $page[$region]['doubleclick_floodlight_std'] = array(
          '#markup' => $std_pix,
        );
      }

      if ($show_unique) {
        $uniq_pix = doubleclick_floodlight_unique_pixel($account_id, $type, $cat);
        $page[$region]['doubleclick_floodlight_uniq'] = array(
          '#markup' => $uniq_pix,
        );
      }
    }
  }
}

/**
 * Helper function to get the Standard doubleclick pixel.
 */
function doubleclick_floodlight_standard_pixel($account_id, $type, $cat) {
  $script = array(
    '<script type="text/javascript">',
    'var axel = Math.random() + "";',
    'var a = axel * 10000000000000;',
    'document.write(\'<iframe src="https://' . $account_id . '.fls.doubleclick.net/activityi;src=' . $account_id . ';type=' . $type . ';cat=' .$cat. ';ord=\' + a + \'?" width="1" height="1" frameborder="0" style="display:none"></iframe>\');',
    '</script>',
    '<noscript>',
    '<iframe src="https://' . $account_id . '.fls.doubleclick.net/activityi;src=' . $account_id . ';type=' . $type . ';cat=' .$cat. ';ord=1?" width="1" height="1" frameborder="0" style="display:none"></iframe>',
    '</noscript>',
  );
  return implode(PHP_EOL, $script);
}

/**
 * Helper function to get the Unique doubleclick pixel.
 */
function doubleclick_floodlight_unique_pixel($account_id, $type, $cat) {
  $script = array(
    '<script type="text/javascript">',
    'var axel = Math.random() + "";',
    'var a = axel * 10000000000000;',
    'document.write(\'<iframe src="https://' . $account_id . '.fls.doubleclick.net/activityi;src=' . $account_id . ';type=' . $type . ';cat=' .$cat. ';ord=1;num=\' + a + \'?" width="1" height="1" frameborder="0" style="display:none"></iframe>\');',
    '</script>',
    '<noscript>',
    '<iframe src="https://' . $account_id . '.fls.doubleclick.net/activityi;src=' . $account_id . ';type=' . $type . ';cat=' . $cat . ';ord=1;num=1?" width="1" height="1" frameborder="0" style="display:none"></iframe>',
    '</noscript>'
  );
  return implode(PHP_EOL, $script);
}
