doubleclick_floodlight.settings:
  type: mapping
  label: Settings
  mapping:
    doubleclick_floodlight_enabled:
      type: integer
    doubleclick_floodlight_account_id:
      type: string
    doubleclick_floodlight_show_standard:
      type: integer
    doubleclick_floodlight_show_unique:
      type: integer
    doubleclick_floodlight_type:
      type: string
    doubleclick_floodlight_cat:
      type: string
    doubleclick_floodlight_region:
      type: string
